#!/usr/bin/env python3
"""Run the synthetic PCOS backtest suite and print stable JSON.

The fixture lives at tests/data/pcos_backtest_cases.json and is generated by
scripts/build_pcos_backtest_cases.py. Cases pin a fixed evaluation anchor so
contraception-recency suppressors are deterministic across runs.
"""

from __future__ import annotations

import json
import sys
from datetime import UTC, datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from core.analyzers import (  # noqa: E402
    PcosBacktestFold,
    PcosBacktestSummary,
    evaluate_pcos,
    load_pcos_backtest_fixture,
    pcos_backtest_summary_to_dict,
)

FIXED_EVALUATION_TIME = datetime(2026, 5, 11, tzinfo=UTC)


def main() -> int:
    cases = load_pcos_backtest_fixture()
    folds: list[PcosBacktestFold] = []
    for case in cases:
        result = evaluate_pcos(
            case.subject_id,
            list(case.observations),
            years_since_menarche=case.years_since_menarche,
            evaluated_at=FIXED_EVALUATION_TIME,
        )
        folds.append(
            PcosBacktestFold(
                case_id=case.case_id,
                expected_status=case.expected_status,
                predicted_status=result.status,
                status_match=result.status == case.expected_status,
                confidence=result.confidence,
                age_group_used=result.age_group_used,
                rotterdam_self_report_feature_count=result.rotterdam_self_report_feature_count,
                meets_irregularity_rule=result.meets_irregularity_rule,
                meets_hyperandrogenism_rule=result.meets_hyperandrogenism_rule,
            )
        )
    summary = PcosBacktestSummary(
        fold_count=len(folds),
        exact_match_rate=sum(1 for fold in folds if fold.status_match) / len(folds) if folds else 0.0,
        folds=tuple(folds),
    )
    print(json.dumps(pcos_backtest_summary_to_dict(summary), indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
